[versions]
agp = "8.5.1"
appcompatV7 = "28.0.0"
constraintLayout = "2.0.4"
kotlin = "1.9.0"
appcompat = "1.6.1"
material = "1.10.0"

[libraries]
appcompat-v7 = { module = "com.android.support:appcompat-v7", version.ref = "appcompatV7" }
constraint-layout = { module = "com.android.support.constraint:constraint-layout", version.ref = "constraintLayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
